# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(max_length=64)),
                ('cpu_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disksize', models.CharField(max_length=32)),
                ('diskused', models.CharField(max_length=32)),
                ('diskaval', models.CharField(max_length=32)),
                ('diskuse', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('hostip', models.GenericIPAddressField()),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Cpu')),
                ('diskinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Disk')),
            ],
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memtotal', models.CharField(max_length=32)),
                ('memfree', models.CharField(max_length=32)),
                ('mempercent', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='meminfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Mem'),
        ),
    ]
