# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=16)),
                ('phone', models.IntegerField(blank=True, default='12345678910', null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
            preserve_default=False,
        ),
    ]
